name: Release

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
    

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    permissions:
      contents: write # to create release 
      issues: write # to post issue comments
      pull-requests: write # to create pull request 
      
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install Dependencies
        run: npm ci

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: npm ci && npm run release
        env:
          GITHUB_TOKEN: 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
          NPM_TOKEN: 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